

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SiburTest.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DataBaseContainer : DbContext
{
    public DataBaseContainer()
        : base("name=DataBaseContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Employee> EmployeeSet { get; set; }

    public virtual DbSet<Department> DepartmentSet { get; set; }

}

}

